obj-$(CONFIG_FB_MSM_MIPI_R63306_PANEL_TMD_MDV20) += mipi_tmd_video_wxga_mdv20.o
obj-$(CONFIG_FB_MSM_MIPI_R63306_PANEL_TMD_MDV22) += mipi_tmd_video_wxga_mdv22.o
obj-$(CONFIG_FB_MSM_MIPI_R63306_PANEL_TMD_MDW30) += mipi_tmd_video_wxga_mdw30.o
obj-$(CONFIG_FB_MSM_MIPI_R63306_PANEL_SHARP_LS043K3SX01) += mipi_sharp_video_wxga_ls043k3sx01.o

EXTRA_CFLAGS += -Idrivers/video/msm

